version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/matatabi_app
      - gem_data:/usr/local/bundle
    depends_on:
      - db
  db:
    build: ./docker/db
    container_name: db
    hostname: db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "db-volume:/var/lib/mysql"
volumes:
  db-volume:
  gem_data:
